### ISSUE TITLE
双击放大

### ISSUE THREAD

**Issue by guangmingxiong9999** [ailiwean/NBZxing#11]
双击放大的时候放到最大了，建议逐级递增放大

**Comment by guangmingxiong9999** [comment]
1.颜色较深的二维码，对于相机聚焦不太好的手机，扫描很快，但是聚焦好的反而没那么快
2.聚焦好的手机 图片容易发生拉伸，不太好的没事
![QQ图片20200821150229](https://user-images.githubusercontent.com/19978284/90862022-602c5c00-e3bf-11ea-8df6-015b9e7ffb6a.jpg)

**Comment by ailiwean** [comment]
什么情况下图片拉伸了

**Comment by guangmingxiong9999** [comment]
@ailiwean  扫码完成跳转到下一页，然后再返回重新扫描，偶尔会出现这种拉伸

**Comment by ailiwean** [comment]
已修复

**Comment by guangmingxiong9999** [comment]
是要重新发版本吧，我引用  implementation 'com.github.ailiwean:NBZxing:0.0.21' 这个还是会拉伸

**Comment by ailiwean** [comment]
我发一版吧
