### ISSUE TITLE
oppo findx 崩溃

### ISSUE THREAD

**Issue by guangmingxiong9999** [ailiwean/NBZxing#13]
08-26 14:50:35.438 26583 26710 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.SortedSet.last()' on a null object reference
08-26 14:50:35.438 26583 26710 E AndroidRuntime: 	at com.google.android.cameraview.Camera2.prepareImageReader(Camera2.java:497)
08-26 14:50:35.438 26583 26710 E AndroidRuntime: 	at com.google.android.cameraview.Camera2.start(Camera2.java:219)
08-26 14:50:35.438 26583 26710 E AndroidRuntime: 	at com.google.android.cameraview.CameraView.start(CameraView.java:325)
08-26 14:50:35.438 26583 26710 E AndroidRuntime: 	at com.google.android.cameraview.BaseCameraView$openCamera$1.run(BaseCameraView.kt:193)
08-26 14:50:35.438 26583 26710 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
08-26 14:50:35.438 26583 26710 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-26 14:50:35.438 26583 26710 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:200)

**Comment by guangmingxiong9999** [comment]
大佬，能帮忙看下吗，这个比较急

**Comment by ailiwean** [comment]
![image](https://user-images.githubusercontent.com/39707263/91277208-183d7880-e7b5-11ea-9a8c-59acc28a3db7.png)
你在这里断下，参数发我

**Comment by ailiwean** [comment]
@guangmingxiong9999

**Comment by guangmingxiong9999** [comment]
@ailiwean 我没这款手机，我用wetest测试的，等下我看能不能打出日志

**Comment by guangmingxiong9999** [comment]
@ailiwean 日志打不出来，他是在之前就崩溃了
