### ISSUE TITLE
 无法识别测试二维码

### ISSUE THREAD

**Issue by liuqiangdd** [ailiwean/NBZxing#14]
我下载了 Demo，扫描您给的测试二维码，都扫不出来。测试手机小米 10Pro

**Comment by ailiwean** [comment]
不存在啊， 你扫的那个

**Comment by ailiwean** [comment]
@liuqiangdd

**Comment by ailiwean** [comment]
最后那个确实不容易扫，  这块膨胀算法实在太难处理了 ， 目前只能做到让手机发生轻微晃动，采集的数据自行弥补才行， 后期想办法优化， 其他几个应该都是秒扫

**Comment by ailiwean** [comment]
sorry  ,我失误了，  自己写的demo 库都没依赖全。  马上打个新的

**Comment by liuqiangdd** [comment]
> 最后那个确实不容易扫， 这块膨胀算法实在太难处理了 ， 目前只能做到让手机发生轻微晃动，采集的数据自行弥补才行， 后期想办法优化， 其他几个应该都是秒扫

奇怪了，我昨天下载的确实扫不出来，一个都扫不出来。今天又下载了下，除了最后一个都扫出来了。
