### ISSUE TITLE
Android8.0 使用USB摄像头无法打开预览界面

### ISSUE THREAD

**Issue by luoruncai** [ailiwean/NBZxing#19]
我使用android8.0 的机器，接入一个USB摄像头，打不开扫码的预览界面。
然后在Camera2.java文件中的private boolean chooseCameraIdByFacing() 中屏蔽：
level == CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY
这个判断，接着去掉下面的 (internal == internalFacing) 判断，可以正常打开

但是这样处理后，扫码容易出现扫码不出来

**Comment by ailiwean** [comment]
应该不太容易解决，  进群情况具体发我下，这里不方便

**Comment by ailiwean** [comment]
@luoruncai
