### ISSUE TITLE
是否能设置不是全屏？

### ISSUE THREAD

**Issue by goodsfile** [ailiwean/NBZxing#21]
![image](https://user-images.githubusercontent.com/16220397/97796780-4aee6c00-1c51-11eb-972d-16484c55df61.png)
这个能实现吗

**Comment by ailiwean** [comment]
可以的 大小随意给 @goodsfile     记得star

**Comment by goodsfile** [comment]
已star，预览时会不会因为SurfaceView高度变窄，出现预览被拉伸？我用zxing 库会有这个问题 @ailiwean

**Comment by ailiwean** [comment]
不会的，  TextureView。  只要能跑起来，任何机型都不会拉伸。  放心使用

**Comment by goodsfile** [comment]
好的
