### ISSUE TITLE
内存抖动这么严重

### ISSUE THREAD

**Issue by Marx-Hong** [ailiwean/NBZxing#26]
内存抖动严重，使用过程中发热明显。虽说这是什么kotlin版本，但看源码，也就其中小部分几个类用了kotlin，百分之九十以上是java

**Comment by Marx-Hong** [comment]
jitpack仓库的也是内存抖动明显，而且页面卡顿明显；测试机型：小米Mix2s android 10

**Comment by ailiwean** [comment]
扫码这块发生幅度大的抖动很正常的， 每帧的数据也要1920*1080个字节， 然后基于这些实时帧数据又会并发一些其他内存占用操作，    算是个取舍吧， 占用内存小就是降低采样清晰程度，并发改成串行， 这种体验完全不行。    至于发热卡顿， 跟cpu有关系过热导致卡顿，  一般扫码也不会持续太长时间。

**Comment by ailiwean** [comment]
不过后边可以发一版， 降低下线程数量和缓存池长度

**Comment by Marx-Hong** [comment]
嗯，gradle引用移动手机摄像头会卡，demo倒是体验挺好，就是抖动也好厉害，发热和卡顿应该就是这方面引起的，gc太频繁。如果发热和卡顿能优化，还是很好的。项目很好，提这个问题是觉得可以优化

**Comment by ailiwean** [comment]
嗯， 已经想到了一个可优化的地方， 大概能降低30%的内存占用，    你可以试下将输出比例改成4:3 有没有得到改善，  其他的扫码库用的都是4:3,     但是实测16 ：9 效率上是最好的

**Comment by Marx-Hong** [comment]
好的，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aiWean"<notifications@github.com&gt;; 
发送时间: 2020年11月30日(星期一) 晚上6:11
收件人: "ailiwean/NBZxing"<NBZxing@noreply.github.com&gt;; 
抄送: "洪文宇"<243633227@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ailiwean/NBZxing] 内存抖动这么严重 (#26)





 
嗯， 已经想到了一个可优化的地方， 大概能降低30%的内存占用，    你可以试下将输出比例改成4:3 有没有得到改善，  其他的扫码库用的都是4:3,     但是实测16 ：9 效率上是最好的

**Comment by Marx-Hong** [comment]
刚刚分析了一下，内存抖动好像是com.ailiwean.core.zxing.core.common这个包下引起的，这个应该是zxing的源码吧？
