### ISSUE TITLE
能不能支持一下连续扫码？

### ISSUE THREAD

**Issue by kagurasansan** [ailiwean/NBZxing#27]

**Comment by ailiwean** [comment]
重新启用相机就行了，    自己处理完上次扫码结果后调用 onCameraResume @kagurasansan

**Comment by ailiwean** [comment]
如果是类似打点不间断相机，就得自己改代码了，   后续可以加上

**Comment by kagurasansan** [comment]
我试了一下如果调用onCameraResume 相机会闪烁 我改在resultback的时候重新调用了start就可以连续扫码了

**Comment by farmercz** [comment]
> 我试了一下如果调用onCameraResume 相机会闪烁 我改在resultback的时候重新调用了start就可以连续扫码了

调用onCameraResume会黑屏闪烁一下，调用start不会黑屏，但是也会闪烁一下。
