### ISSUE TITLE
扫描结果不对时，如何继续扫码

### ISSUE THREAD

**Issue by TwilightKHQ** [ailiwean/NBZxing#32]
想问一下，现在如果扫码结果不对的话，要继续扫码的话要如何处理呢？

**Comment by ailiwean** [comment]
一般不会出现扫描结果不对 ，    你可以在onedreader中调大那个次数  有个数字3试着往大调点10或者更高的，  
出现这种问题就是复杂二维码扫成条码， 如果你不用条码 直接调成仅二维码，   如果

**Comment by ailiwean** [comment]
扫描结果里处理 不合理的

**Comment by TwilightKHQ** [comment]
我没描述清楚，二维码能正确识别出来，但是识别结果不是我想要的(扫描的二维码不是我想要的类型)，
我需要再次扫描时，怎么重新打开相机？
直接调用syncLifeStart会导致页面重启

**Comment by ailiwean** [comment]
opencamera 方法

**Comment by ailiwean** [comment]
@TwilightKHQ

**Comment by TwilightKHQ** [comment]
👌 问题解决 谢谢
