### ISSUE TITLE
点击手动对焦该如何处理呢？

### ISSUE THREAD

**Issue by TwilightKHQ** [ailiwean/NBZxing#38]
有时候自动对焦总是对不上，自动变焦又不太合适，该如何实现点击手动对焦呢？

**Comment by ailiwean** [comment]
Camera2，Camera1 中有改变测光区域的方法， 调焦跟这个很类似需要提供一个Rect，CameraView中有写将View对应到一个矩形方法，  点击的话你可以稍微改一下，或者用一个View模拟，最后得到矩形就行了， 最后把矩形配置进去重新调焦就行，    细节你可以调研一下，   我近期没有时间呀，    欢迎pr

**Comment by ailiwean** [comment]
对了，   默认是修改调焦区域的，对应扫描区域，   你只需点击重新对焦就行

**Comment by TwilightKHQ** [comment]
OK，我调整一下

**Comment by TwilightKHQ** [comment]
没太看懂是怎么把点击位置和对焦位置对应起来，直接用的模拟View
感觉二维码扫描界面不太好放view，暂时就不pr了
