### ISSUE TITLE
使用freeZxingView识别图片失败的时候会崩溃

### ISSUE THREAD

**Issue by qihigh** [ailiwean/NBZxing#43]
当使用FreeZxingView识别图片的时候，识别结果会回调到 onParseResult(Result)中。
但是在result不为空，但是result.text为空的时候，就会崩溃，因为
resultBackFile(content: String) {}
这个方法参数没有声明为 String?。

修复办法：需要修改方法声明为String?
    protected open fun resultBackFile(content: String?) {}
或者
    resultBackFile(result.text ?: "")

**Comment by ailiwean** [comment]
用 0.2.2  这个版本处理了 @qihigh

**Comment by qihigh** [comment]
回复好快，确实修复了。谢谢！！
