### ISSUE TITLE
com.ailiwean.core.zxing.core.Result.getText()' on a null object reference 空指针

### ISSUE THREAD

**Issue by panruifeng1990** [ailiwean/NBZxing#44]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.ailiwean.core.zxing.core.Result.getText()' on a null object reference
	at com.ailiwean.core.able.XQRScanAble.a(XQRScanAble.java:41)

**Comment by ailiwean** [comment]
用0.2.2

**Comment by panruifeng1990** [comment]
好的 我更换一下

**Comment by ailiwean** [comment]
留个star，谢谢
