### ISSUE TITLE
code 39类型的条形码扫不出来

### ISSUE THREAD

**Issue by darrendl** [ailiwean/NBZxing#46]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/10044297/113388123-36f59480-93c0-11eb-9c7c-b824e77026ac.png">

**Comment by ailiwean** [comment]
在 QRTypeConfig 这个类里配置加进去就行了 @darrendl

**Comment by darrendl** [comment]
确实扫出来了，太感谢了
