### ISSUE TITLE
您好！我不想使用您的相机自动缩放和手电筒功能

### ISSUE THREAD

**Issue by if-time** [ailiwean/NBZxing#47]
我不想使用您的相机自动缩放和手电筒功能，我应该怎么在代码中去掉他们？

**Comment by ailiwean** [comment]
自动缩放可以反射移除AbleManager里的AutoZoomAble，  手电筒就把这个View设置隐藏就行  @if-time

**Comment by ailiwean** [comment]
我记错了是移除 XQRScanZoomAble，  然后添加它的子类XQRScanAble
