### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by guangmingxiong9999** [ailiwean/NBZxing#9]
经过我最近用遍github排名的库来说，这个库是最快最好的，对于我们这种印刷的书本里面的很深的二维码来说，扫描也是很快的。其他库，要么不能扫，要么很慢。建议出个java版本，更新下Api，完善下界面。可以去公众号推广下。对于扫码要求比较高的开发来说很不错。

**Comment by ailiwean** [comment]
谢谢 谢谢🙏 ，我又满血满蓝了 💪💪
